routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    // Route::get('/', function () {
    //     return view('welcome');
    // });
/*
    Route::get('/', function () {
        return redirect()->route('crud.index');
    });

    Route::get('/test-crud', function () {
        return view('crud');
    });
*/
    Route::resource('crud', 'Web\CRUDController');
    
    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('{path?}', function () {
        return view('index');
    })->where('path', '(.*)');

app/Http/Controllers/Api/CRUDController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\CRUDRepository;

class CRUDController extends Controller
{
    protected $CRUDRepo;

    public function __construct(CRUDRepository $CRUDRepo)
    {
        $this->CRUDRepo = $CRUDRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->CRUDRepo->index();
        return response()->json(['status' => 'success', 'posts' => $posts]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only('title', 'content');
        $post = $this->CRUDRepo->create($data);
        return response()->json(['status' => 'success', 'post' => $post]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = $this->CRUDRepo->find($id);
        return response()->json(['status' => 'success', 'post' => $post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->only('title', 'content');
        $post = $this->CRUDRepo->update($id, $data);
        if ($post) {
            return response()->json(['status' => 'success']);
        }
        return response()->json(['status' => 'error', 'message' => 'Post Not Found'], 404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->CRUDRepo->delete($id);
        if ($result) {
            return response()->json(['status' => 'success']);
        }
        return response()->json(['status' => 'error', 'message' => 'Post Not Found'], 404);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Web/CRUDController.php
<?php
    
    namespace App\Http\Controllers\Web;
    
    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Repositories\CRUDRepository;
    
    class CRUDController extends Controller
    {
        protected $CRUDRepo;
        
        public function __construct(CRUDRepository $CRUDRepo)
        {
            $this->CRUDRepo = $CRUDRepo;
        }

        /**
         * Check Login Page
         *
         * @return \Illuminate\Http\Response
         */
        public function home()
        {
            return view('crud.home');
        }
        
        
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            $posts = $this->CRUDRepo->index();
            return view('crud.index', ['posts' => $posts]);
        }
        
        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            return view('crud.create');
        }
        
        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
            $data = $request->only('title', 'content');
            $post = $this->CRUDRepo->create($data);
            return redirect()->route('crud.show', $post->id);
        }
        
        /**
         * Display the specified resource.
         *
         * @param  int $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            $post = $this->CRUDRepo->find($id);
            return view('crud.show', ['post' => $post]);
        }
        
        /**
         * Show the form for editing the specified resource.
         *
         * @param  int $id
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            $post = $this->CRUDRepo->find($id);
            return view('crud.edit', ['post' => $post]);
        }
        
        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request $request
         * @param  int $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $id)
        {
            $data = $request->only('title', 'content');
            $post = $this->CRUDRepo->update($id, $data);
            if ($post) {
                return redirect()->route('crud.show', $id);
            }
            return redirect()->route('crud.index');
        }
        
        /**
         * Remove the specified resource from storage.
         *
         * @param  int $id
         * @return \Illuminate\Http\Response
         */
        public function destroy($id)
        {
            $result = $this->CRUDRepo->delete($id);
            return redirect()->route('crud.index');
        }
    }

resources/views/crud.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Testing</title>
</head>
<body>
    
</body>
</html>

resources/views/crud/create.blade.php
@extends('layouts.CRUD')
@section('title', '新增')
@section('content')
    <a class="btn btn-success" href="{{ route('crud.index') }}">返回</a>
    <br/>
    <form action="{{ route('crud.store') }}" method="post">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="title">標題123</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label for="content">內容</label>
            <textarea class="form-control" name="content" cols="30" rows="10"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">送出</button>
    </form>
@endsection

resources/views/crud/edit.blade.php
@extends('layouts.CRUD')
@section('title', '編輯')
@section('content')
<form action="{{ route('crud.update', $post->id) }}" method="post">
    {{ method_field('put') }}
    {{ csrf_field() }}
    <div class="form-group">
        <label for="title">標題</label>
        <input type="text" class="form-control" name="title" value="{{ $post->title }}">
    </div>
    <div class="form-group">
        <label for="content">內容</label>    
        <textarea class="form-control" name="content" cols="30" rows="10">{{ $post->content }}</textarea>
    </div>
    <a class="btn btn-default" href="{{ route('crud.show', $post->id) }}">返回</a>
    <button type="submit" class="btn btn-primary">送出</button>
</form>
@endsection

resources/views/crud/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/crud/index.blade.php
@extends('layouts.CRUD')
@section('title', '主頁')
@section('content')
<a class="btn btn-primary" href="{{ route('crud.create') }}">新增</a>
<br/>
<br/>
<table class="table table-hover">
    <thead>
        <th>標題</th>
        <th>內容</th>
    </thead>
    <tbody>
        @foreach ($posts as $post)
        <tr onclick="window.location = '{{ route('crud.show', $post->id) }}'">
            <td>{{ $post->title }}</td>
            <td>{{ $post->content }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/crud/indexTest.blade.php
@extends('layouts.appTest')
@section('title', 'CRUD首頁')
@section('put-something-inside')
    <div>我在這</div>
@endsection
@section('content')
    <div>我是內容</div>
@endsection

resources/views/crud/show.blade.php
@extends('layouts.CRUD')
@section('title', '查看')
@section('content')
<h1>{{ $post->title }}</h1>
<div>{{ $post->content }}</div>
<a class="btn btn-default" href="{{ route('crud.index') }}">返回</a>
<a class="btn btn-primary" href="{{ route('crud.edit', $post->id) }}">編輯</a>
<button class="btn btn-danger" data-toggle="modal" data-target="#myModal">刪除</button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
            <h4>是否刪除？</h4>
        </div>
        <div class="modal-footer">
            <form action="{{ route('crud.destroy', $post->id) }}" method="post">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submmit" class="btn btn-danger">刪除</button>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>IRONMAN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">IRONMAN</a>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div id="app">
            <app/>
        </div>
    </div>
</body>
<script src="{{ asset('js/app.js') }}"></script>
</html>

resources/views/layouts/CRUD.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="{{ app()->getLocale() }}"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <script src="{{ asset('js/app.js') }}"></script>
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">IRONMAN</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    @yield('content')
</div>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/appTest.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <script src="{{ asset('js/app.js') }}"></script>
    <title>@yield('title')</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">IRONMAN</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    @section('put-something-inside')
        <div></div>
    @show
    @yield('content')
</div>
</body>
</html>